version: "3.0"

services:

    nginx1:
        image: nginx
        container_name: nginx1
        ports:
            - 8081:80
        volumes:
            - ./index1.html:/usr/share/nginx/html/index.html

    nginx2:
        image: nginx
        container_name: nginx2
        ports:
            - 8082:80
        volumes:
            - ./index2.html:/usr/share/nginx/html/index.html
            